import { createSlice } from '@reduxjs/toolkit'
import { v4 } from 'uuid'

const initialState = {
    products: [
        {
            rating: 3.5,
            id: v4(),
            path: 'grifo.png',
            name: 'Grifo',
            type: 'Night lamp',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'leviosa.png',
            name: 'Leviosa',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'lolito.png',
            name: 'Lolito',
            type: 'Luxury big sofa',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'muggo.png',
            name: 'Muggo',
            type: 'Small mug',
            cost: '150.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'pingky.png',
            name: 'Pingky',
            type: 'Cute bed set',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'potty.png',
            name: 'Potty',
            type: 'Minimalist flower pot',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'respira.png',
            name: 'Respira',
            type: 'Outdoor bar table and stool',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'syltherine.png',
            name: 'Syltherine',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '3.500.000',
            discount: '-30%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        }, {

            rating: 3.5,
            id: v4(),
            path: 'grifo.png',
            name: 'Grifo2',
            type: 'Night lamp',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'leviosa.png',
            name: 'Leviosa2',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'lolito.png',
            name: 'Lolito2',
            type: 'Luxury big sofa',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'muggo.png',
            name: 'Muggo2',
            type: 'Small mug',
            cost: '150.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'pingky.png',
            name: 'Pingky2',
            type: 'Cute bed set',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'potty.png',
            name: 'Potty2',
            type: 'Minimalist flower pot',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'respira.png',
            name: 'Respira2',
            type: 'Outdoor bar table and stool',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'syltherine.png',
            name: 'Syltherine2',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '3.500.000',
            discount: '-30%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'grifo.png',
            name: 'Grifo3',
            type: 'Night lamp',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'leviosa.png',
            name: 'Leviosa3',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'lolito.png',
            name: 'Lolito3',
            type: 'Luxury big sofa',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'muggo.png',
            name: 'Muggo3',
            type: 'Small mug',
            cost: '150.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'pingky.png',
            name: 'Pingky3',
            type: 'Cute bed set',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'potty.png',
            name: 'Potty3',
            type: 'Minimalist flower pot',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'respira.png',
            name: 'Respira3',
            type: 'Outdoor bar table and stool',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'syltherine.png',
            name: 'Syltherine3',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '3.500.000',
            discount: '-30%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'grifo.png',
            name: 'Grifo4',
            type: 'Night lamp',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'leviosa.png',
            name: 'Leviosa4',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'lolito.png',
            name: 'Lolito4',
            type: 'Luxury big sofa',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'muggo.png',
            name: 'Muggo4',
            type: 'Small mug',
            cost: '150.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'pingky.png',
            name: 'Pingky4',
            type: 'Cute bed set',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'potty.png',
            name: 'Potty4',
            type: 'Minimalist flower pot',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'respira.png',
            name: 'Respira4',
            type: 'Outdoor bar table and stool',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'syltherine.png',
            name: 'Syltherine4',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '3.500.000',
            discount: '-30%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'grifo.png',
            name: 'Grifo5',
            type: 'Night lamp',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: v4(),
            path: 'leviosa.png',
            name: 'Leviosa5',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '',
            new: false,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'lolito.png',
            name: 'Lolito5',
            type: 'Luxury big sofa',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {
            rating: 3.5,
            id: v4(),
            path: 'muggo.png',
            name: 'Muggo5',
            type: 'Small mug',
            cost: '150.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,

        },
        {

            rating: 3.5,
            id: v4(),
            path: 'pingky.png',
            name: 'Pingky5',
            type: 'Cute bed set',
            cost: '7.000.000',
            oldCost: '14.000.000',
            discount: '-50%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {
            rating: 3.5,
            id: v4(),
            path: 'potty.png',
            name: 'Potty5',
            type: 'Minimalist flower pot',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {
            rating: 3.5,
            id: v4(),
            path: 'respira.png',
            name: 'Respira5',
            type: 'Outdoor bar table and stool',
            cost: '500.000',
            oldCost: '',
            new: true,
            discount: '',
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {
            rating: 3.5,
            id: v4(),
            path: 'syltherine.png',
            name: 'Syltherine5',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '3.500.000',
            discount: '-30%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        },
        {

            rating: 3.5,
            id: 'single_product_id',
            path: 'triple_chair.png',
            name: 'Asgaard sofa',
            type: 'Stylish cafe chair',
            cost: '2.500.000',
            oldCost: '3.500.000',
            discount: '-30%',
            new: false,
            salesPackage: '1 sectional sofa',
            modelNumber: 'TFCBLIGRBL6SRHS',
            secondaryMaterial: 'Solid Wood',
            configuration: 'L-shaped',
            upholsteryMaterial: 'Fabric + Cotton',
            upholsteryColor: 'Bright Grey & Lion',
            fillingMaterial: 'Foam',
            finishType: 'Bright Grey & Lion',
            adjustableHeadrest: 'No',
            maximumLoadCapacity: '280 KG',
            originOfManufacture: 'India',
            width: '265.32 cm',
            height: '76 cm',
            depth: '167.76 cm',
            weight: '45 KG',
            seatHeight: '41.52 cm',
            legHeight: '5.46 cm',
            warrantySummary: '1 Year Manufacturing Warranty',
            warrantyServiceType: 'For Warranty Claims or Any Product Related Issues Please Email at operations@trevifurniture.com',
            coveredinWarranty: 'Warranty Against Manufacturing Defect',
            notCoveredinWarranty: 'The Warranty Does Not Cover Damages Due To Usage Of The Product Beyond Its Intended Use And Wear & Tear In The Natural Course Of Product Usage.',
            domesticWarranty: '1 Year',
            reviews: 204,
        }
    ]

}

export const allProductSlice = createSlice({
    name: 'all_products',
    initialState,
    reducers: {
        changeRatingValue: (state, action) => {
            const { id, newRating } = action.payload;
            if (newRating >= 0.5) {
                state.products = state.products.map(product => {
                    if (product.id === id) {
                        return { ...product, rating: newRating };
                    }
                    return product;
                });
            }

        }
    },
})

export const { changeRatingValue } = allProductSlice.actions
export default allProductSlice.reducer